### ISSUE TITLE
bug: BlueOS resets to factory version

### ISSUE THREAD

**Issue by odedezra** [bluerobotics/BlueOS#2465] opened 2024-03-19 10:54 UTC
### Bug description

really not sure what causes this to happen, nothing special was done on the system prior to this. it also happened on another system and another laptop. logs attached. thanks!
[system_logs.zip](https://github.com/bluerobotics/BlueOS/files/14649516/system_logs.zip)

### Steps to reproduce

start system normally

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by ES-Alexander** [comment] 2024-03-21 15:03
This seems to be a duplicate of #2248, which has been fixed.

If you install the latest 1.2 beta (requires Pirate Mode) of the core BlueOS image (using the [BlueOS Version](https://blueos.cloud/docs/blueos/1.1/advanced-usage/#blueos-version) page) and then click the "Update Bootstrap" button that appears next to the active BlueOS version it should resolve the issue:

<img width="876" alt="Screenshot 2024-03-22 at 2 00 34 am" src="https://github.com/bluerobotics/BlueOS/assets/25898329/781f2a1d-b03b-489c-9245-739ff900630e">

Closing this Issue for now (as a duplicate), but feel free to follow up if you encounter the problem again after updating BlueOS core and bootstrap.

**Closed by ES-Alexander** 2024-03-21 15:03 UTC
Labels: bug, ui, triage
